// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package resolver_query_log_config_association

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.ResolverQueryLogConfigID, b.ko.Spec.ResolverQueryLogConfigID) {
		delta.Add("Spec.ResolverQueryLogConfigID", a.ko.Spec.ResolverQueryLogConfigID, b.ko.Spec.ResolverQueryLogConfigID)
	} else if a.ko.Spec.ResolverQueryLogConfigID != nil && b.ko.Spec.ResolverQueryLogConfigID != nil {
		if *a.ko.Spec.ResolverQueryLogConfigID != *b.ko.Spec.ResolverQueryLogConfigID {
			delta.Add("Spec.ResolverQueryLogConfigID", a.ko.Spec.ResolverQueryLogConfigID, b.ko.Spec.ResolverQueryLogConfigID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ResolverQueryLogConfigRef, b.ko.Spec.ResolverQueryLogConfigRef) {
		delta.Add("Spec.ResolverQueryLogConfigRef", a.ko.Spec.ResolverQueryLogConfigRef, b.ko.Spec.ResolverQueryLogConfigRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ResourceID, b.ko.Spec.ResourceID) {
		delta.Add("Spec.ResourceID", a.ko.Spec.ResourceID, b.ko.Spec.ResourceID)
	} else if a.ko.Spec.ResourceID != nil && b.ko.Spec.ResourceID != nil {
		if *a.ko.Spec.ResourceID != *b.ko.Spec.ResourceID {
			delta.Add("Spec.ResourceID", a.ko.Spec.ResourceID, b.ko.Spec.ResourceID)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ResourceRef, b.ko.Spec.ResourceRef) {
		delta.Add("Spec.ResourceRef", a.ko.Spec.ResourceRef, b.ko.Spec.ResourceRef)
	}

	return delta
}
