---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-route53resolver-reader
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - route53resolver.services.k8s.aws
  resources:
  - resolverendpoints
  verbs:
  - get
  - list
  - watch
