// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package resolver_rule

import (
	"bytes"
	"fmt"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}
	if !reflect.DeepEqual(a.ko.Spec.Associations, b.ko.Spec.Associations) {
		delta.Add("Spec.Associations", a.ko.Spec.Associations, b.ko.Spec.Associations)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DomainName, b.ko.Spec.DomainName) {
		delta.Add("Spec.DomainName", a.ko.Spec.DomainName, b.ko.Spec.DomainName)
	} else if a.ko.Spec.DomainName != nil && b.ko.Spec.DomainName != nil {
		if *a.ko.Spec.DomainName != *b.ko.Spec.DomainName {
			delta.Add("Spec.DomainName", a.ko.Spec.DomainName, b.ko.Spec.DomainName)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ResolverEndpointID, b.ko.Spec.ResolverEndpointID) {
		delta.Add("Spec.ResolverEndpointID", a.ko.Spec.ResolverEndpointID, b.ko.Spec.ResolverEndpointID)
	} else if a.ko.Spec.ResolverEndpointID != nil && b.ko.Spec.ResolverEndpointID != nil {
		if *a.ko.Spec.ResolverEndpointID != *b.ko.Spec.ResolverEndpointID {
			delta.Add("Spec.ResolverEndpointID", a.ko.Spec.ResolverEndpointID, b.ko.Spec.ResolverEndpointID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RuleType, b.ko.Spec.RuleType) {
		delta.Add("Spec.RuleType", a.ko.Spec.RuleType, b.ko.Spec.RuleType)
	} else if a.ko.Spec.RuleType != nil && b.ko.Spec.RuleType != nil {
		if *a.ko.Spec.RuleType != *b.ko.Spec.RuleType {
			delta.Add("Spec.RuleType", a.ko.Spec.RuleType, b.ko.Spec.RuleType)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.Tags, b.ko.Spec.Tags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}
	if !reflect.DeepEqual(a.ko.Spec.TargetIPs, b.ko.Spec.TargetIPs) {
		delta.Add("Spec.TargetIPs", a.ko.Spec.TargetIPs, b.ko.Spec.TargetIPs)
	}

	return delta
}
