// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type Action string

const (
	Action_ALLOW Action = "ALLOW"
	Action_BLOCK Action = "BLOCK"
	Action_ALERT Action = "ALERT"
)

type AutodefinedReverseFlag string

const (
	AutodefinedReverseFlag_ENABLE                     AutodefinedReverseFlag = "ENABLE"
	AutodefinedReverseFlag_DISABLE                    AutodefinedReverseFlag = "DISABLE"
	AutodefinedReverseFlag_USE_LOCAL_RESOURCE_SETTING AutodefinedReverseFlag = "USE_LOCAL_RESOURCE_SETTING"
)

type BlockOverrideDNSType string

const (
	BlockOverrideDNSType_CNAME BlockOverrideDNSType = "CNAME"
)

type BlockResponse string

const (
	BlockResponse_NODATA   BlockResponse = "NODATA"
	BlockResponse_NXDOMAIN BlockResponse = "NXDOMAIN"
	BlockResponse_OVERRIDE BlockResponse = "OVERRIDE"
)

type FirewallDomainImportOperation string

const (
	FirewallDomainImportOperation_REPLACE FirewallDomainImportOperation = "REPLACE"
)

type FirewallDomainListStatus string

const (
	FirewallDomainListStatus_COMPLETE               FirewallDomainListStatus = "COMPLETE"
	FirewallDomainListStatus_COMPLETE_IMPORT_FAILED FirewallDomainListStatus = "COMPLETE_IMPORT_FAILED"
	FirewallDomainListStatus_IMPORTING              FirewallDomainListStatus = "IMPORTING"
	FirewallDomainListStatus_DELETING               FirewallDomainListStatus = "DELETING"
	FirewallDomainListStatus_UPDATING               FirewallDomainListStatus = "UPDATING"
)

type FirewallDomainUpdateOperation string

const (
	FirewallDomainUpdateOperation_ADD     FirewallDomainUpdateOperation = "ADD"
	FirewallDomainUpdateOperation_REMOVE  FirewallDomainUpdateOperation = "REMOVE"
	FirewallDomainUpdateOperation_REPLACE FirewallDomainUpdateOperation = "REPLACE"
)

type FirewallFailOpenStatus string

const (
	FirewallFailOpenStatus_ENABLED                    FirewallFailOpenStatus = "ENABLED"
	FirewallFailOpenStatus_DISABLED                   FirewallFailOpenStatus = "DISABLED"
	FirewallFailOpenStatus_USE_LOCAL_RESOURCE_SETTING FirewallFailOpenStatus = "USE_LOCAL_RESOURCE_SETTING"
)

type FirewallRuleGroupAssociationStatus string

const (
	FirewallRuleGroupAssociationStatus_COMPLETE FirewallRuleGroupAssociationStatus = "COMPLETE"
	FirewallRuleGroupAssociationStatus_DELETING FirewallRuleGroupAssociationStatus = "DELETING"
	FirewallRuleGroupAssociationStatus_UPDATING FirewallRuleGroupAssociationStatus = "UPDATING"
)

type FirewallRuleGroupStatus string

const (
	FirewallRuleGroupStatus_COMPLETE FirewallRuleGroupStatus = "COMPLETE"
	FirewallRuleGroupStatus_DELETING FirewallRuleGroupStatus = "DELETING"
	FirewallRuleGroupStatus_UPDATING FirewallRuleGroupStatus = "UPDATING"
)

type IPAddressStatus string

const (
	IPAddressStatus_CREATING                  IPAddressStatus = "CREATING"
	IPAddressStatus_FAILED_CREATION           IPAddressStatus = "FAILED_CREATION"
	IPAddressStatus_ATTACHING                 IPAddressStatus = "ATTACHING"
	IPAddressStatus_ATTACHED                  IPAddressStatus = "ATTACHED"
	IPAddressStatus_REMAP_DETACHING           IPAddressStatus = "REMAP_DETACHING"
	IPAddressStatus_REMAP_ATTACHING           IPAddressStatus = "REMAP_ATTACHING"
	IPAddressStatus_DETACHING                 IPAddressStatus = "DETACHING"
	IPAddressStatus_FAILED_RESOURCE_GONE      IPAddressStatus = "FAILED_RESOURCE_GONE"
	IPAddressStatus_DELETING                  IPAddressStatus = "DELETING"
	IPAddressStatus_DELETE_FAILED_FAS_EXPIRED IPAddressStatus = "DELETE_FAILED_FAS_EXPIRED"
	IPAddressStatus_UPDATING                  IPAddressStatus = "UPDATING"
)

type MutationProtectionStatus string

const (
	MutationProtectionStatus_ENABLED  MutationProtectionStatus = "ENABLED"
	MutationProtectionStatus_DISABLED MutationProtectionStatus = "DISABLED"
)

type ResolverAutodefinedReverseStatus string

const (
	ResolverAutodefinedReverseStatus_ENABLING                               ResolverAutodefinedReverseStatus = "ENABLING"
	ResolverAutodefinedReverseStatus_ENABLED                                ResolverAutodefinedReverseStatus = "ENABLED"
	ResolverAutodefinedReverseStatus_DISABLING                              ResolverAutodefinedReverseStatus = "DISABLING"
	ResolverAutodefinedReverseStatus_DISABLED                               ResolverAutodefinedReverseStatus = "DISABLED"
	ResolverAutodefinedReverseStatus_UPDATING_TO_USE_LOCAL_RESOURCE_SETTING ResolverAutodefinedReverseStatus = "UPDATING_TO_USE_LOCAL_RESOURCE_SETTING"
	ResolverAutodefinedReverseStatus_USE_LOCAL_RESOURCE_SETTING             ResolverAutodefinedReverseStatus = "USE_LOCAL_RESOURCE_SETTING"
)

type ResolverDNSSECValidationStatus string

const (
	ResolverDNSSECValidationStatus_ENABLING                               ResolverDNSSECValidationStatus = "ENABLING"
	ResolverDNSSECValidationStatus_ENABLED                                ResolverDNSSECValidationStatus = "ENABLED"
	ResolverDNSSECValidationStatus_DISABLING                              ResolverDNSSECValidationStatus = "DISABLING"
	ResolverDNSSECValidationStatus_DISABLED                               ResolverDNSSECValidationStatus = "DISABLED"
	ResolverDNSSECValidationStatus_UPDATING_TO_USE_LOCAL_RESOURCE_SETTING ResolverDNSSECValidationStatus = "UPDATING_TO_USE_LOCAL_RESOURCE_SETTING"
	ResolverDNSSECValidationStatus_USE_LOCAL_RESOURCE_SETTING             ResolverDNSSECValidationStatus = "USE_LOCAL_RESOURCE_SETTING"
)

type ResolverEndpointDirection string

const (
	ResolverEndpointDirection_INBOUND  ResolverEndpointDirection = "INBOUND"
	ResolverEndpointDirection_OUTBOUND ResolverEndpointDirection = "OUTBOUND"
)

type ResolverEndpointStatus string

const (
	ResolverEndpointStatus_CREATING        ResolverEndpointStatus = "CREATING"
	ResolverEndpointStatus_OPERATIONAL     ResolverEndpointStatus = "OPERATIONAL"
	ResolverEndpointStatus_UPDATING        ResolverEndpointStatus = "UPDATING"
	ResolverEndpointStatus_AUTO_RECOVERING ResolverEndpointStatus = "AUTO_RECOVERING"
	ResolverEndpointStatus_ACTION_NEEDED   ResolverEndpointStatus = "ACTION_NEEDED"
	ResolverEndpointStatus_DELETING        ResolverEndpointStatus = "DELETING"
)

type ResolverEndpointType string

const (
	ResolverEndpointType_IPV6      ResolverEndpointType = "IPV6"
	ResolverEndpointType_IPV4      ResolverEndpointType = "IPV4"
	ResolverEndpointType_DUALSTACK ResolverEndpointType = "DUALSTACK"
)

type ResolverQueryLogConfigAssociationError string

const (
	ResolverQueryLogConfigAssociationError_NONE                   ResolverQueryLogConfigAssociationError = "NONE"
	ResolverQueryLogConfigAssociationError_DESTINATION_NOT_FOUND  ResolverQueryLogConfigAssociationError = "DESTINATION_NOT_FOUND"
	ResolverQueryLogConfigAssociationError_ACCESS_DENIED          ResolverQueryLogConfigAssociationError = "ACCESS_DENIED"
	ResolverQueryLogConfigAssociationError_INTERNAL_SERVICE_ERROR ResolverQueryLogConfigAssociationError = "INTERNAL_SERVICE_ERROR"
)

type ResolverQueryLogConfigAssociationStatus string

const (
	ResolverQueryLogConfigAssociationStatus_CREATING      ResolverQueryLogConfigAssociationStatus = "CREATING"
	ResolverQueryLogConfigAssociationStatus_ACTIVE        ResolverQueryLogConfigAssociationStatus = "ACTIVE"
	ResolverQueryLogConfigAssociationStatus_ACTION_NEEDED ResolverQueryLogConfigAssociationStatus = "ACTION_NEEDED"
	ResolverQueryLogConfigAssociationStatus_DELETING      ResolverQueryLogConfigAssociationStatus = "DELETING"
	ResolverQueryLogConfigAssociationStatus_FAILED        ResolverQueryLogConfigAssociationStatus = "FAILED"
)

type ResolverQueryLogConfigStatus string

const (
	ResolverQueryLogConfigStatus_CREATING ResolverQueryLogConfigStatus = "CREATING"
	ResolverQueryLogConfigStatus_CREATED  ResolverQueryLogConfigStatus = "CREATED"
	ResolverQueryLogConfigStatus_DELETING ResolverQueryLogConfigStatus = "DELETING"
	ResolverQueryLogConfigStatus_FAILED   ResolverQueryLogConfigStatus = "FAILED"
)

type ResolverRuleAssociationStatus string

const (
	ResolverRuleAssociationStatus_CREATING   ResolverRuleAssociationStatus = "CREATING"
	ResolverRuleAssociationStatus_COMPLETE   ResolverRuleAssociationStatus = "COMPLETE"
	ResolverRuleAssociationStatus_DELETING   ResolverRuleAssociationStatus = "DELETING"
	ResolverRuleAssociationStatus_FAILED     ResolverRuleAssociationStatus = "FAILED"
	ResolverRuleAssociationStatus_OVERRIDDEN ResolverRuleAssociationStatus = "OVERRIDDEN"
)

type ResolverRuleStatus string

const (
	ResolverRuleStatus_COMPLETE ResolverRuleStatus = "COMPLETE"
	ResolverRuleStatus_DELETING ResolverRuleStatus = "DELETING"
	ResolverRuleStatus_UPDATING ResolverRuleStatus = "UPDATING"
	ResolverRuleStatus_FAILED   ResolverRuleStatus = "FAILED"
)

type RuleTypeOption string

const (
	RuleTypeOption_FORWARD   RuleTypeOption = "FORWARD"
	RuleTypeOption_SYSTEM    RuleTypeOption = "SYSTEM"
	RuleTypeOption_RECURSIVE RuleTypeOption = "RECURSIVE"
)

type ShareStatus string

const (
	ShareStatus_NOT_SHARED     ShareStatus = "NOT_SHARED"
	ShareStatus_SHARED_WITH_ME ShareStatus = "SHARED_WITH_ME"
	ShareStatus_SHARED_BY_ME   ShareStatus = "SHARED_BY_ME"
)

type SortOrder string

const (
	SortOrder_ASCENDING  SortOrder = "ASCENDING"
	SortOrder_DESCENDING SortOrder = "DESCENDING"
)

type Validation string

const (
	Validation_ENABLE                     Validation = "ENABLE"
	Validation_DISABLE                    Validation = "DISABLE"
	Validation_USE_LOCAL_RESOURCE_SETTING Validation = "USE_LOCAL_RESOURCE_SETTING"
)
